### ISSUE TITLE
Project template

### ISSUE THREAD

**Issue by markknol** [skial/FD_SamplePlugin#1]
This is a great project, I'm very interested to test this out! I have not much c# experience, so if this works it would simplify creating FlashDevelop stuff.

Anyway I don't know the exact state, but this repository as project template would complete it; so you can do _project > new project > FlashDevelop plugin_.

**Comment by back2dos** [comment]
Ooooooh, yes please. Can FD live-reload plugins?

**Comment by markknol** [comment]
@back2dos Hehe that would be great, but afaik you have to restart to test. You might help/ask  @flashdevelop for such feature :smile:

**Comment by skial** [comment]
@markknol that would be great, I'll look into how to create a project template. The majority of my C# has been gained from this project, so pretty basic!

It would be great to have @waneck hxcs to build the project instead of my quick macro solution.

**Comment by skial** [comment]
I've created a new repo for the [project template](https://github.com/skial/FD_PluginTemplate). Currently it fails to compile due to how `build/Tool.hx` is written, but it appears to be creating projects correctly :smile:.

**Comment by markknol** [comment]
Great, will test soon!

**Comment by markknol** [comment]
Btw, can maybe remove the word "FlashDevelop" from the project template name? We are secretly working on a custom distribution called "HaxeDevelop" :wink: sstt

**Comment by skial** [comment]
Good idea, I'll do that tomorrow. :smile:

**Comment by Neverbirth** [comment]
Currently FD cannot live reload a plugin, but we could look into adding special support for this type of project where we try to reload the plugin (the developer can always do something wrong and reloading may fail, of course).

**Comment by back2dos** [comment]
@Neverbirth That's great news!
